version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - db
    networks: 
      - matcha
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks: 
      - matcha
    environment:
      - .env

  db:
    image: postgres:15-alpine
    container_name: matcha_db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/database/matcha.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matcha

networks: 
  matcha:
    name: matcha
    driver: bridge

volumes:
  postgres_data:
