-- All enums types

CREATE TYPE "genders" AS ENUM (
  'female',
  'male',
  'other'
);

CREATE TYPE "orientations" AS ENUM (
  'men',
  'women',
  'both'
);

CREATE TYPE "type_tokens" AS ENUM (
  'verification',
  'reset'
);

CREATE TYPE "type_notifs" AS ENUM (
  'like',
  'view',
  'message',
  'match',
  'unlike'
);

-- All tables

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "biography" text,
  "email" varchar(255) UNIQUE NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "birthdate" date,
  "gender" genders,
  "sexual_preference" orientations NOT NULL DEFAULT 'both',
  "fame_rating" integer DEFAULT 0,
  "longitude" decimal(11,8),
  "latitude" decimal(10,8),
  "is_online" boolean DEFAULT false,
  "is_verified" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "last_connection" timestamp
);

CREATE TABLE "tags" (
  "tag_id" SERIAL PRIMARY KEY,
  "tag_name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "tokens" (
  "token_id" SERIAL PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "type_token" type_tokens NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp NOT NULL,

  FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE
);

CREATE TABLE "conversations" (
  "conversation_id" SERIAL PRIMARY KEY,
  "user1_id" bigint NOT NULL,
  "user2_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),

  FOREIGN KEY ("user1_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("user2_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,

  -- Protège contre les doublons logiques (A-B et B-A)
  CHECK (user1_id < user2_id),

  -- Protège contre les doublons physiques (A-B et A-B)
  UNIQUE ("user1_id", "user2_id")

);

CREATE TABLE "messages" (
  "message_id" BIGSERIAL PRIMARY KEY,
  "conversation_id" integer NOT NULL,
  "sender_id" bigint NOT NULL,
  "content" text NOT NULL,
  "is_read" boolean DEFAULT false,
  "sent_at" timestamp DEFAULT (now()),

  FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("conversation_id") ON DELETE CASCADE,
  FOREIGN KEY ("sender_id") REFERENCES "users" ("user_id") ON DELETE CASCADE
);

CREATE TABLE "views" (
  "view_id" BIGSERIAL PRIMARY KEY,
  "viewer_id" bigint NOT NULL,
  "viewed_id" bigint NOT NULL,
  "view_at" timestamp NOT NULL DEFAULT (now()),

  FOREIGN KEY ("viewer_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("viewed_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,

  -- L'utilisateur ne doit pas se voir lui-même
  -- Le <> signifie "différent de"
  CHECK ("viewer_id" <> "viewed_id")
);

CREATE TABLE "likes" (
  "user_id" bigint,
  "liked_user_id" bigint,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "liked_user_id"),

  FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("liked_user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,

  CHECK ("user_id" <> "liked_user_id")
);

CREATE TABLE "pictures" (
  "picture_id" SERIAL PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "is_profile_picture" boolean NOT NULL DEFAULT false,
  "file_path" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),

  FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE
);

CREATE TABLE "notifications" (
  "notification_id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "from_user_id" bigint NOT NULL,
  "type_notif" type_notifs NOT NULL,
  "is_read" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),

  FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("from_user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE
);

CREATE TABLE "blocks" (
  "blocker_id" bigint,
  "blocked_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("blocker_id", "blocked_id"),

  FOREIGN KEY ("blocker_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("blocked_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,

  CHECK ("blocker_id" <> "blocked_id")
);

CREATE TABLE "reports" (
  "reporter_id" bigint,
  "reported_id" bigint,
  "reason" text,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("reporter_id", "reported_id"),

  FOREIGN KEY ("reporter_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("reported_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,

  CHECK ("reporter_id" <> "reported_id")
);

CREATE TABLE "user_tags" (
  "user_id" bigint,
  "tag_id" integer,
  PRIMARY KEY ("user_id", "tag_id"),

  FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("tag_id") REFERENCES "tags" ("tag_id") ON DELETE CASCADE
);

-- All indexes - to optimize queries

CREATE INDEX ON "users" ("email");

CREATE INDEX ON "users" ("username");

CREATE INDEX ON "messages" ("conversation_id");

CREATE INDEX ON "views" ("viewer_id");

CREATE INDEX ON "views" ("viewed_id");

CREATE INDEX ON "views" ("viewer_id", "viewed_id");

CREATE INDEX ON "likes" ("user_id");

CREATE INDEX ON "likes" ("liked_user_id");

CREATE INDEX ON "pictures" ("user_id");

CREATE INDEX ON "pictures" ("user_id", "is_profile_picture");

CREATE INDEX ON "notifications" ("user_id", "is_read");

CREATE INDEX ON "blocks" ("blocker_id");

-- Il va prendre en compte seulement les lignes où is_profile_picture = true et s'assurera qu'il n'y a qu'une seule photo de profil par user
CREATE UNIQUE INDEX idx_user_profile_picture ON "pictures" ("user_id") WHERE "is_profile_picture" = true;

-- All comments

COMMENT ON TABLE "conversations" IS 'Les conversations ne concernent que 2 users
CHECK: Prévoir les duplicatas
'; -- ✅

COMMENT ON TABLE "views" IS 'L''utilisateur ne doit pas se voir lui-même'; -- ✅

COMMENT ON COLUMN "views"."viewer_id" IS 'Utilisateurs que J''AI VISITÉ'; -- ✅

COMMENT ON COLUMN "views"."viewed_id" IS 'Utilisateurs qui M''ONT VISITÉ'; -- ✅

COMMENT ON TABLE "likes" IS 'L''utilisateur ne doit pas se like lui-même'; -- ✅

COMMENT ON TABLE "pictures" IS 'Les users ont 5 photos maximum et ont UNE photo de profile'; -- À gérer dans le backend

COMMENT ON COLUMN "notifications"."user_id" IS 'Utilisateur qui REÇOIT la notif'; -- ✅

COMMENT ON COLUMN "notifications"."from_user_id" IS 'Utilisateur qui GÉNÈRE la notif'; -- ✅

COMMENT ON TABLE "blocks" IS 'L''utilisateur ne doit pas se block lui-même'; -- ✅

COMMENT ON TABLE "reports" IS 'L''utilisateur ne doit pas se report lui-même'; -- ✅

